sentence_level1 = [
"1, 2, 3, 4, 5, 6, 7, 8, 9 [il, i, sam, sa, o, yuk, chil, pal, gu]",
"Sorry 죄송합니다 [jesonghamnida]",
"The game will be paused for a moment 게임 잠시 중단됩니다 [Game jamsi jungdan demnida]",
"I will proceed again after verifying this 확인 후, 다시 진행하겠습니다 [hwagin hu, dasi jinhaeng hagetseumnida]",
"Thank you for waiting so long 오래 기다려 주셔서 감사합니다 [orae gidaryeo jusyeoseo gamsahamnida]",
"The game is starting again 게임 다시 시작합니다 [Game dasi sijakamnida]",
"Hello dear Players 플레이어 여러분 안녕하세요 [Player yeoreobun annyeonghaseyo]",
"I am dealer OO your for this session 이번 세션 딜러 OO입니다 [ibeon session dealer (your name) imnida]",
"It’s time to place your bets 베팅 시간입니다 [betting sigan imnida]",
"The new round is open 새 라운드가 오픈되었습니다 [sae round-ga open de eot seumnida]",
"Please place your bets 베팅해 주세요 [betting hae juseyo]",
"Please place your side bets now as well 사이드 베팅도 지금 해 주세요 [side betting do jigeum hae juseyo]",
"There are 5 seconds left to place your bet 베팅 5초 남았습니다 [betting o cho namatseumnida]",
"Betting time has closed 배팅 시간 마감했습니다 [betting sigan magam haetseumnida]",
"Betting is closed, and the game is about to begin 베팅 마감하고 게임 시작합니다 [betting magamhago game sijakamnida]",
"Wishing you good luck 행운을 빌어요 [haenguneul bireoyo]",]
