sentence_level1 = [
"1, 2, 3, 4, 5, 6, 7, 8, 9 [il, i, sam, sa, o, yuk, chil, pal, gu]",
"Sorry 죄송합니다 [jesonghamnida]",
"The game will be paused for a moment 게임 잠시 중단됩니다 [Game jamsi jungdan demnida]",
"I will proceed again after verifying this 확인 후, 다시 진행하겠습니다 [hwagin hu, dasi jinhaeng hagetseumnida]",
"Thank you for waiting so long 오래 기다려 주셔서 감사합니다 [orae gidaryeo jusyeoseo gamsahamnida]",
"The game is starting again 게임 다시 시작합니다 [Game dasi sijakamnida]",
"Hello dear Players 플레이어 여러분 안녕하세요 [Player yeoreobun annyeonghaseyo]",
"I am dealer OO your for this session 이번 세션 딜러 OO입니다 [ibeon session dealer (your name) imnida]",
"It’s time to place your bets 베팅 시간입니다 [betting sigan imnida]",
"The new round is open 새 라운드가 오픈되었습니다 [sae round-ga open de eot seumnida]",
"Please place your bets 베팅해 주세요 [betting hae juseyo]",
"Please place your side bets now as well 사이드 베팅도 지금 해 주세요 [side betting do jigeum hae juseyo]",
"There are 5 seconds left to place your bet 베팅 5초 남았습니다 [betting o cho namatseumnida]",
"Betting time has closed 배팅 시간 마감했습니다 [betting sigan magam haetseumnida]",
"Betting is closed, and the game is about to begin 베팅 마감하고 게임 시작합니다 [betting magamhago game sijakamnida]",
"Wishing you good luck 행운을 빌어요 [haenguneul bireoyo]",
"I will deal the card to the player 플레이어 카드 드리겠습니다 [player card deuriget seumnida]",
"I will deal the card to the banker 뱅커 카드 드리겠습니다 [banker card deuriget seumnida]",
"Player receives an extra card, then 플레이어 추가 카드 받고 [player chuga card bad ggo]", 
"banker receives an extra card, then 뱅커 추가 카드 받고 [banker chuga card bad ggo]", 
"banker wins with a natural 8 뱅커 네추럴 8로 승리합니다 [baker natural pal ro seungnihamnida]", 
"player wins with a natural 8 플레이어 네추럴 8로 승리합니다 [baker natural pal ro seungnihamnida]",
"banker wins with a natural 9 뱅커 네추럴 9로 승리합니다 [baker natural gu ro seungnihamnida]", 
"player wins with a natural 9 플레이어 네추럴 9로 승리합니다 [baker natural gu ro seungnihamnida]",
"Player wins 플레이어 승 [player seung]",
"Banker wins 뱅커 승 [banker seung]",
"Congratulations to the winners 승리하신 분들 축하드립니다 [seungnihasin bundeul chukadeurimnida]", 
"Congratulations on the player’s successful bet 플레이어 베팅 성공 축하드립니다 [player betting seonggong chukadeurimnida]",
"Congratulations on the banker’s successful bet 뱅커 베팅 성공 축하드립니다 [banker betting seonggong chukadeurimnida]",
"Congratulations on the tie’s successful bet 타이 베팅 성공 축하드립니다 [tie betting seonggong chukadeurimnida]",
"The payout for tie bet is 8x 타이 배당은 8배 입니다 [Tie baedang eun yeodeol bbae imnida]",
"Congratulations on side bet as well 사이드 베팅도 축하드립니다 [side betting do chuka deurimnida]",
"The payout for the Any Pair bet is 5x 애니 페어 배당은 5배입니다 [any pair baedangeun daseot bae imnida]", 
"The payout for the player Pair bet is 11x 플레이어 페어 배당은 11배 입니다 [player pair baedangeun yeol-han bae imnida]", 
"The payout for the banker Pair bet is 11x 뱅커 페어 배당은 11배 입니다 [banker pair baedangeun yeol-han bae imnida]",
"The payout for the Lucky Six bet is 12x 럭키 식스 배당은 12배 입니다 [lucky six baedangeun yeol-du bae imnida]",
"The payout for the Lucky Six bet is 20x 럭키 식스 배당은 20배 입니다 [lucky six baedangeun seu-mu bae imnida]", 
"The payout for the perfect Pair bet is 25x 퍼펙트 페어 배당은 25배 입니다 [perfect pair baedangeun seu-mul-da-seot bae imnida]", 
"The payout for the both perfect Pair bet is 200x 양 퍼펙트 페어 배당은 200배 입니다 [yang perfect pair baedangeun i-baek bae imnida]", 
]
