sentence_level1 = [
"1, 2, 3, 4, 5, 6, 7, 8, 9 [il, i, sam, sa, o, yuk, chil, pal, gu]",
"Sorry 죄송합니다 [jesonghamnida]",
"The game will be paused for a moment 게임 잠시 중단됩니다 [Game jamsi jungdan demnida]",
"I will proceed again after verifying this 확인 후, 다시 진행하겠습니다 [hwagin hu, dasi jinhaeng hagetseumnida]",
"I am waiting for assistance 도움을 기다리고 있습니다 [doumeul gidarigo itsseum nida]",
"Thank you for waiting so long 오래 기다려 주셔서 감사합니다 [orae gidaryeo jusyeoseo gamsahamnida]",
"Thank you for waiting so long 오랫동안 기다려 주셔서 감사합니다 [oraetdongan gidaryeo jusyeoseo gamsahamnida]",
"The game is starting again 게임 다시 시작합니다 [Game dasi sijakamnida]",
"Hello dear Players 플레이어 여러분 안녕하세요 [Player yeoreobun annyeonghaseyo]",
"I am dealer OO your for this session 이번 세션을 맡은 딜러 OO입니다 [ibeon sessioneul mateun dealer (your name) imnida]",
"I am dealer OO your for this session 이번 세션 딜러 OO입니다 [ibeon session dealer (your name) imnida]",
"It’s time to place your bets 베팅 시간입니다 [betting sigan imnida]",
"Betting time is open 베팅 시간 오픈 되었습니다 [betting sigan open de eot sseumnida ]",
"The new round is open 새 라운드가 오픈되었습니다 [sae round-ga open de eot seumnida]",
"The new round is open 새로운 라운드가 오픈되었습니다 [saeroun round-ga open de eot seumnida]",
"Everyone lt’s time to place your bets 여러분, 베팅 할 시간입니다 [yeoreobun, betting hal sigan imnida]",
"Please place your bets 베팅해 주세요 [betting hae juseyo]",
"Please place your side bets now as well 사이드 베팅도 지금 해 주세요 [side betting do jigeum hae juseyo]",
"There are 5 seconds left to place your bet 베팅 5초 남았습니다 [betting o cho namatseumnida]",
"Betting time has closed 배팅 시간 마감했습니다 [betting sigan magam haetseumnida]",
"Betting is closed, and the game is about to begin 베팅 마감하고 게임 시작합니다 [betting magamhago game sijakamnida]",
"Wishing you good luck 행운을 빌어요 [haenguneul bireoyo]",
"Betting is closed, and good luck 베팅 마감하고 행운을 빌어요 [betting magamhago haenguneul bireoyo]",
"I will deal the card to the player 플레이어 카드 드리겠습니다 [player card deuriget seumnida]",
"I will deal the card to the banker 뱅커 카드 드리겠습니다 [banker card deuriget seumnida]",
"Player receives an extra card, then 플레이어 추가 카드 받고 [player chuga card bad ggo]", 
"banker receives an extra card, then 뱅커 추가 카드 받고 [banker chuga card bad ggo]",   
"banker wins with a natural 8 뱅커 네추럴 8로 승리합니다 [baker natural pal ro seungnihamnida]", 
"player wins with a natural 8 플레이어 네추럴 8로 승리합니다 [baker natural pal ro seungnihamnida]",
"banker wins with a natural 9 뱅커 네추럴 9로 승리합니다 [baker natural gu ro seungnihamnida]", 
"player wins with a natural 9 플레이어 네추럴 9로 승리합니다 [baker natural gu ro seungnihamnida]",
"Player wins 플레이어 승 [player seung]",
"Banker wins 뱅커 승 [banker seung]",
"Congratulations to the winners 승리하신 분들 축하드립니다 [seungnihasin bundeul chukadeurimnida]", 
"Congratulations on the player’s successful bet 플레이어 베팅 성공 축하드립니다 [player betting seonggong chukadeurimnida]",
"Congratulations on the banker’s successful bet 뱅커 베팅 성공 축하드립니다 [banker betting seonggong chukadeurimnida]",
"Congratulations on the player bet 플레이어 베팅 축하드립니다 [player betting chukadeurimnida]",
"Congratulations on the banker bet 뱅커 베팅 축하드립니다 [banker betting chukadeurimnida]",
"It is tie 타이입니다 [Tie imnida]",
"It is tie game 타이 게임입니다 [Tie game imnida]",
"Congratulations on the tie’s successful bet 타이 베팅 성공 축하드립니다 [tie betting seonggong chukadeurimnida]",
"Congratulations on the tie bet 타이 베팅 축하드립니다 [tie betting chukadeurimnida]",
"The payout for tie bet is 8x 타이 배당은 8배 입니다 [Tie baedang eun yeodeol bbae imnida]",
"It pays out 8 times the bet amount on a tie 타이 베팅 금액의 8배로 지급됩니다 [Tie betting geumaege yeodeol bbae ro ji geup dem nida]",
"Congratulations on side bet as well 사이드 베팅도 축하드립니다 [side betting do chuka deurimnida]",
"The payout for the Any Pair bet is 5x 애니 페어 배당은 5배입니다 [any pair baedangeun daseot bae imnida]", 
"The payout for the player Pair bet is 11x 플레이어 페어 배당은 11배 입니다 [player pair baedangeun yeol-han bae imnida]", 
"The payout for the banker Pair bet is 11x 뱅커 페어 배당은 11배 입니다 [banker pair baedangeun yeol-han bae imnida]",
"The payout for the Lucky Six bet is 12x 럭키 식스 배당은 12배 입니다 [lucky six baedangeun yeol-du bae imnida]",
"The payout for the Lucky Six bet is 20x 럭키 식스 배당은 20배 입니다 [lucky six baedangeun seu-mu bae imnida]", 
"The payout for the perfect Pair bet is 25x 퍼펙트 페어 배당은 25배 입니다 [perfect pair baedangeun seu-mul-da-seot bae imnida]", 
"The payout for the both perfect Pair bet is 200x 양 퍼펙트 페어 배당은 200배 입니다 [yang perfect pair baedangeun i-baek bae imnida]", 
"The cutting card has been dealt 컷팅 카드 나왔습니다 [cutting card nawadsseumnida]",
"I'll change the shoe after this game 이번 게임 마치고 슈 체인지합니다 [i-beon game machigo shoe change hammida]",
"It is the last game of this shoe 이번 슈 마지막 게임입니다 [i-beon shoe magimak game minida]",
"I am changing the shoe 슈 체인지 합니다 [shoe change hammida]",
"I'll change the shoe 슈 체인지 할게요 [shoe change halgeyo]",
"I Changed the shoe 슈 체인지 했습니다 [shoe change haedsseumnida]",
"It is the new shoe 새로운 슈 입니다 [saeroun shoe imnida]",
"It is the new shoe 새로운 슈 입니다 [sae shoe imnida]",
"I’m going to burn some cards 카드 버닝 할게요 [card burning halgeyo]",
"I’m going to burn some cards and starting a game 카드 버닝하고 게임 시작합니다 [card burning hago game sijakamnida]",
"I’m burning 1 card 1장 버닝합니다 [han jang burning hamnida]", 
"I’m burning 2 cards 2장 버닝합니다 [du jang burning hamnida]", 
"I’m burning 3 cards 3장 버닝합니다 [se jang burning hamnida]", 
"I’m burning 4 cards 4장 버닝합니다 [ne jang burning hamnida]", 
"I’m burning 5 cards 5장 버닝합니다 [daseot jang burning hamnida]", 
"I’m burning 6 cards 6장 버닝합니다 [yeoseot jang burning hamnida]", 
"I’m burning 7 cards 7장 버닝합니다 [il-gop jang burning hamnida]", 
"I’m burning 8 cards 8장 버닝합니다 [yeo-deol jang burning hamnida]", 
"I’m burning 9 cards 9장 버닝합니다 [ahop jang burning hamnida]", 
"I’m burning 10 cards 10장 버닝합니다 [yeol jang burning hamnida]", 
"I burned 1 card in total 총 1장 버닝했습니다 [chong han jang burning haedsseumnida]", 
"I burned 2 cards in total 총 2장 버닝했습니다 [chong du jang burning haedsseumnida]", 
"I burned 3 cards in total 총 3장 버닝했습니다 [chong se jang burning haedsseumnida]",  
"I burned 4 cards in total 총 4장 버닝했습니다 [chong ne jang burning haedsseumnida]", 
"I burned 5 cards in total 총 5장 버닝했습니다 [chong daseot jang burning haedsseumnida]",  
"I burned 6 cards in total 총 6장 버닝했습니다 [chong yeoseot jang burning haedsseumnida]",  
"I burned 7 cards in total 총 7장 버닝했습니다 [chong il-gop jang burning haedsseumnida]",  
"I burned 8 cards in total 총 8장 버닝했습니다 [chong yeo-deol jang burning haedsseumnida]",  
"I burned 9 cards in total 총 9장 버닝했습니다 [chong ahop jang burning haedsseumnida]",  
"I burned 10 cards in total 총 10장 버닝했습니다 [chong yeol jang burning haedsseumnida]",  
"We’re changing the dealer 딜러 체인지합니다 [Dealer change hammida]",
"Wish you luck with the pretty dealer (next dealer name) 예쁜 OO딜러와 행운을 빌어요 [yeppeun (oo) dealer wa Haenguneul bireoyo]",
"Wish you luck with the beautiful dealer (next dealer name) 아름다 OO딜러와 행운을 빌어요 [areumdaun (oo) dealer wa Haenguneul bireoyo]",
  
]
